# Default theme for txxtv
# This theme matches the built-in default with sensible terminal colors

# Active/selected elements - cursors, highlighted nodes, selections
active:
  fg: white
  bg: blue
  modifiers: [bold]

# Normal content - regular text, unselected nodes
normal:
  # Uses terminal default colors

# Label text - field names in info panel
label:
  fg: yellow

# Tree selection mode indicator
mode_tree:
  fg: cyan
  modifiers: [bold]

# Text selection mode indicator
mode_text:
  fg: green
  modifiers: [bold]

# Error and important messages
error:
  fg: red
  modifiers: [bold]

# Title/header bar
title:
  fg: black
  bg: cyan
  modifiers: [bold]

# Info panel background
panel_bg:
  fg: white
  bg: black

# Borders (currently unused, but included for completeness)
border:
  # Uses terminal default colors
